WIP 2

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,11 +8,19 @@ source "$directory/docker/utilities/domain"
 source "$directory/docker/utilities/profiles"
 source "$directory/docker/utilities/env"
 
-check_required_commands "docker" "readlink"
-assign_permissions
-update_env "/docker/.env" "WORKING_DIR" "$directory"
+check_required_commands "docker"
+update_env "$directory/docker/.env" "WORKING_DIR" "$directory"
+
+if [ $# -eq 0 ]; then
+  echo -e "${RED}Error: No command provided.${NC}"
+  exit 1
+fi
 
 case "$1" in
+permissions|perm|permisson)
+  assign_permissions
+  echo -e "${GREEN}Permissions have been assigned.${NC}"
+  ;;
 domain)
   while true; do
     configure_server
@@ -28,12 +36,12 @@ profiles)
   for service in "${!services_and_profiles[@]}"; do
     process_service "$service"
   done
-
   echo -e "${GREEN}Setup completed.${NC}"
   ;;
 env)
   env_file="$directory/.env"
-  if [ "$2" = "docker" ]; then
+  target="${2:-}"
+  if [ "$target" = "docker" ]; then
     env_file="$directory/docker/.env"
   fi
   process_env_file "$env_file"
